### ISSUE TITLE
Update.py Run Error

### ISSUE THREAD

**Issue by kumarmohan7** [damogranlabs/VS-Code-STM32-IDE#35] opened 2019-11-22 19:55 UTC
Hi 
In Update.py Run i got this error

ERROR (8 seconds).
Unexpected error occured during 'Update' procedure. Exception:
Traceback (most recent call last):
  File "d:/STM32/VSCode_STM32_IDE/STM32CubeMx_WS/STM32_Test/ideScripts/update.py", line 56, in <module>
    makefileData = makefile.getMakefileData(makeExePath, gccExePath)
  File "d:\STM32\VSCode_STM32_IDE\STM32CubeMx_WS\STM32_Test\ideScripts\updateMakefile.py", line 93, in getMakefileData
    projectName = self.getMakefileVariable(makeExePath, gccExePath, self.mkfStr.projectName)[0]
  File "d:\STM32\VSCode_STM32_IDE\STM32CubeMx_WS\STM32_Test\ideScripts\updateMakefile.py", line 366, in getMakefileVariable
    proc = Popen(arguments, stdout=PIPE)
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by schperplata** [comment] 2019-11-23 09:53
Duplicate of https://github.com/damogranlabs/VS-Code-STM32-IDE/issues/35
See https://github.com/damogranlabs/VS-Code-STM32-IDE/issues/34#issuecomment-551302461

**Closed as completed** 2020-04-20 14:24 UTC
Labels: duplicate
